import * as crypto from 'crypto';
import { testCaseStore, observationStore, instrumentStore } from '../repositories';
import { EvidenceService } from './EvidenceService';
import { ReportDataset } from '../types/report';
import { HtmlGenerator } from '../utils/HtmlGenerator';
import { SimplePdfGenerator } from '../utils/SimplePdfGenerator';

export class ReportService {
  public static generateReportData(testCaseId: string, generatedByRole: string): ReportDataset {
    const testCase = testCaseStore.findById(testCaseId);
    if (!testCase) {
      throw new Error(`Test case not found: ${testCaseId}`);
    }

    if (testCase.status !== 'APPROVED') {
      throw new Error('Final test reports can only be generated from test cases in APPROVED status');
    }

    const allObservations = observationStore.findAll().filter(o => o.testCaseId === testCaseId);
    const evidence = EvidenceService.getEvidenceForTestCase(testCaseId);
    const instrument = instrumentStore.findById(testCase.instrumentId);

    // In our simplified mock projection, we project existing observation results or configuration states to compliance summary
    // Since actual evaluations are computed in Phase 8 and stored/returned there, for the purpose of the report dataset
    // We assume the overall verdict maps to the configuration/rules evaluated during workflow approval.
    // Given NAWI architecture requires NO RE-EVALUATION in the reporting phase, we extract from stored compliance outcomes.
    // (In full implementation, these would be saved in a compliance verdict store / directly on test case)

    const baseDataset = {
      reportId: `REP_${testCaseId}_${Date.now()}`,
      testCaseId,
      status: 'FINAL' as const,
      disclaimer: 'Prototype / Pending Official Template Confirmation' as const,
      meta: {
        generatedAt: new Date().toISOString(),
        generatedBy: generatedByRole,
        ruleEngineVersion: 'OIML-R76-1-2006-CORE-V1.0.0-MVP',
        cryptographicSeal: ''
      },
      testDetails: testCase,
      instrumentDetails: instrument,
      observations: allObservations,
      evidence: evidence,
      complianceSummary: {
         // Projecting the status from test case tests Configuration. "NOT STARTED", "IN PROGRESS", "PASS", "FAIL".
         // During approval, WorkflowService validates these.
        weighing: testCase.testConfiguration.weighing,
        eccentricity: testCase.testConfiguration.eccentricity,
        repeatability: testCase.testConfiguration.repeatability,
        tare: testCase.testConfiguration.tare,
        zeroSetting: testCase.testConfiguration.zeroSetting,
        overallVerdict: 'APPROVED'
      }
    };

    // Construct seal string over data properties
    const sealString = JSON.stringify({
      testCase,
      observations: allObservations,
      ruleEngineVersion: baseDataset.meta.ruleEngineVersion
    });

    const hash = crypto.createHash('sha256').update(sealString).digest('hex');
    baseDataset.meta.cryptographicSeal = hash;

    return baseDataset;
  }

  public static generateHtmlReport(testCaseId: string, role: string): string {
    const data = this.generateReportData(testCaseId, role);
    return HtmlGenerator.generate(data);
  }

  public static generatePdfReport(testCaseId: string, role: string): Buffer {
    const data = this.generateReportData(testCaseId, role);
    const lines = [
      `OIML R76 Test Report`,
      `===================`,
      `DISCLAIMER: ${data.disclaimer}`,
      ``,
      `Report ID: ${data.reportId}`,
      `Test Case ID: ${data.testCaseId}`,
      `Status: ${data.status}`,
      `Generated At: ${data.meta.generatedAt}`,
      `Generated By: ${data.meta.generatedBy}`,
      ``,
      `-- Compliance --`,
      `Overall: ${data.complianceSummary.overallVerdict}`,
      `Weighing: ${data.complianceSummary.weighing}`,
      `Eccentricity: ${data.complianceSummary.eccentricity}`,
      `Repeatability: ${data.complianceSummary.repeatability}`,
      `Tare: ${data.complianceSummary.tare}`,
      `Zero Setting: ${data.complianceSummary.zeroSetting}`,
      ``,
      `-- Security --`,
      `Rule Version: ${data.meta.ruleEngineVersion}`,
      `Seal: ${data.meta.cryptographicSeal}`,
      ``,
      `-- Evidence Attached --`,
      `Total items: ${data.evidence.length}`
    ];

    return SimplePdfGenerator.generateDocument(lines);
  }
}
