import { ReportDataset } from '../types/report';

export class HtmlGenerator {
  public static generate(report: ReportDataset): string {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>OIML Test Report - ${report.testCaseId}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
    h1, h2, h3 { color: #2c3e50; }
    .disclaimer { border: 2px dashed #e74c3c; padding: 10px; color: #e74c3c; font-weight: bold; text-align: center; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #bdc3c7; padding: 8px; text-align: left; }
    th { background-color: #ecf0f1; }
    .seal { margin-top: 40px; padding: 20px; background-color: #f9f9f9; border: 1px solid #e1e4e8; border-radius: 4px; }
  </style>
</head>
<body>
  <div class="disclaimer">
    ${report.disclaimer}
  </div>

  <h1>OIML R76 Test Report</h1>
  <p><strong>Report ID:</strong> ${report.reportId}</p>
  <p><strong>Test Case ID:</strong> ${report.testCaseId}</p>
  <p><strong>Status:</strong> ${report.status}</p>

  <h2>Compliance Summary</h2>
  <table>
    <tr><th>Overall Verdict</th><td><strong>${report.complianceSummary.overallVerdict}</strong></td></tr>
    <tr><th>Weighing Test</th><td>${report.complianceSummary.weighing}</td></tr>
    <tr><th>Eccentricity Test</th><td>${report.complianceSummary.eccentricity}</td></tr>
    <tr><th>Repeatability Test</th><td>${report.complianceSummary.repeatability}</td></tr>
    <tr><th>Tare Test</th><td>${report.complianceSummary.tare}</td></tr>
    <tr><th>Zero-Setting Test</th><td>${report.complianceSummary.zeroSetting}</td></tr>
  </table>

  <h2>Cryptographic Seal and Metadata</h2>
  <div class="seal">
    <p><strong>Generated At:</strong> ${report.meta.generatedAt}</p>
    <p><strong>Generated By (Role):</strong> ${report.meta.generatedBy}</p>
    <p><strong>Rule Engine Version:</strong> ${report.meta.ruleEngineVersion}</p>
    <p><strong>SHA-256 Seal:</strong> <code>${report.meta.cryptographicSeal}</code></p>
  </div>
</body>
</html>`;
  }
}
